#!/bin/bash

# Establish the base repository reference directory
THIS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
AKIT_REPOSITORY_DIR="$( dirname $( dirname $THIS_DIR ) )"

echo "THIS_DIR=$THIS_DIR"
echo "AKIT_REPOSITORY_DIR=$AKIT_REPOSITORY_DIR"

# Find and clean all the line endings of python files
if [ -d $AKIT_REPOSITORY_DIR/packages ]; then
    echo "cleaning packages directory..."
    find $AKIT_REPOSITORY_DIR/packages -name '*.py' | xargs --verbose sed -i 's/[[:space:]]*$//'
fi

if [ -d $AKIT_REPOSITORY_DIR/service ]; then
    echo "cleaning service directory..."
    find $AKIT_REPOSITORY_DIR/service -name '*.py' | xargs --verbose sed -i 's/[[:space:]]*$//'
fi

if [ -d $AKIT_REPOSITORY_DIR/tests ]; then
    echo "cleaning tests directory..."
    find $AKIT_REPOSITORY_DIR/tests -name '*.py' | xargs --verbose sed -i 's/[[:space:]]*$//'
fi
